# Block 4 - Grouping And Insight

This notebook teaches how to compare groups, summarise each group, and then state in plain English what the grouped result shows.

**Lesson dataset:** Titanic CSV  
**Dataset file:** `titanic.csv`, supplied in the `datasets` folder with these materials.

When you run this notebook on your own machine, set the path to wherever your copy of `titanic.csv` is saved. If you keep the supplied folder layout, use `../../datasets/titanic.csv`.

This notebook uses one real lesson dataset only: Titanic. Every learner question in this notebook is about Titanic.

The worked examples use a small neutral dummy grouping table. Dummy data is not the lesson data. It only holds simple values so you can see what a grouping operation does before you apply that operation to Titanic.

The notebook has two kinds of code cells:

- Blue worked-example markers = demonstration code with visible output.
- Orange answer markers = your empty answer cell is directly below.

Each concept follows this pattern: plain-English explanation, worked dummy example with visible output containing the labelled breakdown, specific Titanic question, empty learner cell.

## Setup Cells

These are setup cells, not learner answer tasks.

They are pre-filled so the notebook can run cleanly from top to bottom. Run them first.

In [1]:
import pandas as pd

In [2]:
dataset_path = "../../datasets/titanic.csv"

In [3]:
df = pd.read_csv(dataset_path)

In [4]:
dummy_path = "../../datasets/dummy_category_values.csv"
dummy_df = pd.read_csv(dummy_path)

## Concept 1 - What Grouping Means

Grouping means splitting the rows into category buckets, then calculating something inside each bucket. Instead of describing one row at a time, you compare groups.

**Worked dummy example - grouped average**

```python
dummy_df.groupby("category")["value"].mean()
```

**What each part means**

- `dummy_df` = the dummy table.
- `.groupby("category")` = split the rows into category groups.
- `["value"]` = choose the column to summarise inside each group.
- `.mean()` = calculate the average inside each group.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Titanic question.
</div>

In [5]:
dummy_df.groupby("category")["value"].mean()

category
A    11.666667
B     8.000000
C    14.000000
Name: value, dtype: float64

**Question on the lesson dataset - Titanic**

Use grouping on Titanic to compare categories: find the average `Fare` for each `Pclass`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Titanic answer in the empty code cell under this orange box.
</div>

## Concept 2 - Sort Rows With df.sort_values("column")

Sorting reorders the rows by one column so the smallest or largest values are easier to spot. Sorting does not group rows. It simply changes their order.

**Worked dummy example - sort by value**

```python
dummy_df.sort_values("value")
```

**What each part means**

- `dummy_df` = the dummy table.
- `.sort_values()` = the tool that reorders rows.
- `"value"` = the column used as the sorting rule.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Titanic question.
</div>

In [6]:
dummy_df.sort_values("value")

     item category  value  score
4    wrap        A      5      9
2  muffin        B      7      8
3   scone        B      9      5
0   bagel        A     12      4
5   toast        C     14      6
1    roll        A     18      3

**Question on the lesson dataset - Titanic**

Sort Titanic by `Fare` from lowest to highest.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Titanic answer in the empty code cell under this orange box.
</div>

## Concept 3 - Count Categories With df["column"].value_counts()

A category count answers the question: how often does each distinct label appear? This is one of the fastest ways to compare group sizes.

**Worked dummy example - count categories**

```python
dummy_df["category"].value_counts()
```

**What each part means**

- `dummy_df["category"]` = select the category column first.
- `.value_counts()` = count how often each distinct category appears.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Titanic question.
</div>

In [7]:
dummy_df["category"].value_counts()

category
A    3
B    2
C    1
Name: count, dtype: int64

**Question on the lesson dataset - Titanic**

Count how many passengers are in each `Pclass`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Titanic answer in the empty code cell under this orange box.
</div>

## Concept 4 - Group And Average With df.groupby(...)[...].mean()

A grouped average compares the typical value inside each group. The group column creates the buckets. The value column tells pandas what to average inside each bucket.

**Worked dummy example - average by group**

```python
dummy_df.groupby("category")["value"].mean()
```

**What each part means**

- `.groupby("category")` = split rows into groups.
- `["value"]` = choose the values to summarise.
- `.mean()` = calculate the average for each group.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Titanic question.
</div>

In [8]:
dummy_df.groupby("category")["value"].mean()

category
A    11.666667
B     8.000000
C    14.000000
Name: value, dtype: float64

**Question on the lesson dataset - Titanic**

Find the average `Fare` for each `Pclass`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Titanic answer in the empty code cell under this orange box.
</div>

## Concept 5 - Group And Count With df.groupby(...)[...].count()

A grouped count compares how many rows appear inside each group for one chosen column. This is useful when you want group sizes rather than averages.

**Worked dummy example - count by group**

```python
dummy_df.groupby("category")["value"].count()
```

**What each part means**

- `.groupby("category")` = split rows into groups.
- `["value"]` = choose one column to count within each group.
- `.count()` = count the non-missing rows for that column in each group.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Titanic question.
</div>

In [9]:
dummy_df.groupby("category")["value"].count()

category
A    3
B    2
C    1
Name: value, dtype: int64

**Question on the lesson dataset - Titanic**

Count how many `Fare` values appear in each `Pclass`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Titanic answer in the empty code cell under this orange box.
</div>

## Concept 6 - Several Group Summaries At Once With agg()

Sometimes one summary is too thin. `agg()` lets one grouped result show several summary measures at once so the groups are easier to compare.

**Worked dummy example - mean and max together**

```python
dummy_df.groupby("category").agg({"value": ["mean", "max"]})
```

**What each part means**

- `.groupby("category")` = make the groups first.
- `.agg(...)` = ask for several summaries in one result.
- `"value"` = the column being summarised.
- `"mean", "max"` = the summary tools applied to each group.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Titanic question.
</div>

In [10]:
dummy_df.groupby("category").agg({"value": ["mean", "max"]})

              value
               mean max
category
A         11.666667  18
B          8.000000   9
C         14.000000  14

**Question on the lesson dataset - Titanic**

Group Titanic by `Pclass` and calculate more than one summary for `Fare`: use `mean` and `max` together.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Titanic answer in the empty code cell under this orange box.
</div>

## Concept 7 - Turn A Grouped Result Into A Plain-English Finding

A grouped table is evidence, not the final thought. After you create the grouped result, you should say in plain English what the table shows.

**Worked dummy example - grouped result plus finding sentence**

```python
grouped = dummy_df.groupby("category")["value"].mean()
grouped
print("Category A has the highest average value in this dummy table.")
```

**What each part means**

- The grouping line creates the evidence table.
- The printed sentence says, in plain English, what the grouped result shows.
- A grouped result without a sentence is only half-finished analysis.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Titanic question.
</div>

In [11]:
grouped = dummy_df.groupby("category")["value"].mean()
grouped
print("Category A has the highest average value in this dummy table.")

Category A has the highest average value in this dummy table.

**Question on the lesson dataset - Titanic**

Group Titanic by `Pclass` and find the average `Fare`. Then print one plain-English sentence saying which class has the highest average fare in this table.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Titanic answer in the empty code cell under this orange box.
</div>

## Plain-English Findings

After you finish the learner cells, write three observations about what the grouped Titanic results showed.

These should be about the data, not about the commands.

1. 
2. 
3. 

Also write one thing the grouped results do not explain on their own.

-