# Block 2 - Selection And Filtering With Iris

This notebook teaches how to ask the table a yes-or-no question about each row, then keep only the rows that pass.

**Lesson dataset:** Iris CSV  
**Dataset file:** `iris.csv`, supplied in the `datasets` folder with these materials.

When you run this notebook on your own machine, set the path to wherever your copy of `iris.csv` is saved. If you keep the supplied folder layout, use `../../datasets/iris.csv`.

This notebook uses one real lesson dataset only: Iris. Every learner question in this notebook is about Iris.

The worked examples use tiny dummy bread-stock data. Dummy data is not the lesson data. It only holds simple values so you can see what a filtering operation does before you apply that operation to Iris.

The notebook has two kinds of code cells:

- Blue worked-example markers = demonstration code with visible output.
- Orange answer markers = your empty answer cell is directly below.

Each teaching concept follows this pattern: explanation, command panel, labelled code breakdown, worked dummy example with visible output, Iris question, empty learner cell.

## Setup Cells

These are setup cells, not learner answer tasks.

They are pre-filled so the notebook can run cleanly from top to bottom. They do not use the four-part teaching pattern. Run them first.

In [1]:
import pandas as pd

In [2]:
dataset_path = "../../datasets/iris.csv"

In [3]:
df = pd.read_csv(dataset_path)

## Worked Example Setup Cell

This cell prepares the neutral dummy table used in the worked examples.

- `dummy_path` = the file path for the dummy CSV.
- `dummy_df` = the dummy table loaded from that CSV.

This is example setup only. It is not part of the learner task.

In [4]:
dummy_path = "../../datasets/dummy_bread_stock.csv"
dummy_df = pd.read_csv(dummy_path)

## Concept 1 - What Filtering Means

Filtering means asking a yes-or-no question about each row. Before you keep rows, you first need a question that can return `True` or `False` for each row.

### Command Panel

```python
dummy_df["category"] == "bread"
```

**Plain-English meaning**  
Ask whether each row's `category` value is exactly `"bread"`.

**Code breakdown**

- `dummy_df` = the dummy table used for the worked example.
- `[ ]` = square brackets used to select something from the table.
- `"category"` = the column name written as text inside quotes.
- `==` = equals. It checks whether the value matches exactly.
- `"bread"` = the value we want to test for, written as text inside quotes.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Iris question.
</div>

In [5]:
dummy_df["category"] == "bread"

0     True
1     True
2    False
3    False
4     True
Name: category, dtype: bool

**Question on the lesson dataset - Iris**

Use the Iris table in `df` to ask a yes-or-no question about each row: is the `species` value equal to `"setosa"`? Do not keep rows yet. Show the `True` and `False` answers only.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Iris answer in the empty code cell under this orange box.
</div>

## Concept 2 - Outer And Inner Bracket Rule

A filtering line contains two jobs nested inside each other. The inner part asks the row-by-row question. The outer part keeps only the rows where the answer is yes.

### Command Panel

```python
dummy_df[dummy_df["category"] == "bread"]
```

**Plain-English meaning**  
From the dummy table, keep only the rows where the `category` column equals `"bread"`.

**Code breakdown**

- `outer dummy_df[ ... ]` = keep rows from the table.
- `inner dummy_df["category"] == "bread"` = ask the row-by-row question.
- `dummy_df["category"]` = look inside one column before comparing its values.
- `==` = equals.
- `"bread"` = the text value being tested.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Iris question.
</div>

In [6]:
dummy_df[dummy_df["category"] == "bread"]

    item category  count  price
0  bagel    bread     12   0.80
1   roll    bread     18   0.55
4   wrap    bread      5   1.40

**Question on the lesson dataset - Iris**

Use the full outer-and-inner bracket structure to keep only the Iris rows where `species` is `"virginica"`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Iris answer in the empty code cell under this orange box.
</div>

## Concept 3 - Equality Filter With ==

An equality filter keeps rows where one column matches one named value exactly. This is useful when the column contains categories such as labels or names.

### Command Panel

```python
dummy_df[dummy_df["category"] == "bread"]
```

**Plain-English meaning**  
Keep rows where the `category` column equals `"bread"`.

**Code breakdown**

- `dummy_df` = the table being filtered.
- `outer [ ... ]` = keep rows from the table.
- `dummy_df["category"]` = reach into the `category` column.
- `==` = equals.
- `"bread"` = the exact category value to keep.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Iris question.
</div>

In [7]:
dummy_df[dummy_df["category"] == "bread"]

    item category  count  price
0  bagel    bread     12   0.80
1   roll    bread     18   0.55
4   wrap    bread      5   1.40

**Question on the lesson dataset - Iris**

Filter the Iris table so it keeps only the rows where `species` equals `"setosa"`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Iris answer in the empty code cell under this orange box.
</div>

## Concept 4 - Not-Equal Filter With !=

A not-equal filter keeps rows whose value is different from the value you name. It removes one category and keeps the rest.

### Command Panel

```python
dummy_df[dummy_df["category"] != "bread"]
```

**Plain-English meaning**  
Keep rows where the `category` column does not equal `"bread"`.

**Code breakdown**

- `dummy_df` = the table being filtered.
- `outer [ ... ]` = keep rows from the table.
- `dummy_df["category"]` = look inside the `category` column.
- `!=` = does not equal.
- `"bread"` = the category value to exclude.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Iris question.
</div>

In [8]:
dummy_df[dummy_df["category"] != "bread"]

     item category  count  price
2  muffin     cake      7    1.2
3   scone     cake      9    1.1

**Question on the lesson dataset - Iris**

Filter the Iris table so it keeps only the rows where `species` does not equal `"setosa"`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Iris answer in the empty code cell under this orange box.
</div>

## Concept 5 - Greater-Than Filter With >

A greater-than filter is used with numeric values. It keeps only rows where the value is above the threshold you name.

### Command Panel

```python
dummy_df[dummy_df["count"] > 10]
```

**Plain-English meaning**  
Keep rows where the `count` value is greater than `10`.

**Code breakdown**

- `dummy_df` = the table being filtered.
- `dummy_df["count"]` = reach into the numeric `count` column.
- `>` = greater than.
- `10` = the threshold value.
- `outer [ ... ]` = keep rows that pass the test.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Iris question.
</div>

In [9]:
dummy_df[dummy_df["count"] > 10]

    item category  count  price
0  bagel    bread     12   0.80
1   roll    bread     18   0.55

**Question on the lesson dataset - Iris**

Filter the Iris table so it keeps only the rows where `petal_length` is greater than `5.0`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Iris answer in the empty code cell under this orange box.
</div>

## Concept 6 - Less-Than Filter With <

A less-than filter keeps only rows where the numeric value is below the threshold you name.

### Command Panel

```python
dummy_df[dummy_df["price"] < 1.00]
```

**Plain-English meaning**  
Keep rows where the `price` value is less than `1.00`.

**Code breakdown**

- `dummy_df` = the table being filtered.
- `dummy_df["price"]` = reach into the numeric `price` column.
- `<` = less than.
- `1.00` = the threshold value.
- `outer [ ... ]` = keep rows that pass the test.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Iris question.
</div>

In [10]:
dummy_df[dummy_df["price"] < 1.00]

    item category  count  price
0  bagel    bread     12   0.80
1   roll    bread     18   0.55

**Question on the lesson dataset - Iris**

Filter the Iris table so it keeps only the rows where `sepal_width` is less than `3.0`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Iris answer in the empty code cell under this orange box.
</div>

## Concept 7 - Two-Condition AND Filter With &

An AND filter keeps a row only when both conditions are true. If either condition fails, that row is not kept.

### Command Panel

```python
dummy_df[(dummy_df["category"] == "bread") & (dummy_df["price"] > 1.00)]
```

**Plain-English meaning**  
Keep rows where the `category` is `"bread"` and the `price` is greater than `1.00`.

**Code breakdown**

- `outer dummy_df[ ... ]` = keep rows from the table.
- `(dummy_df["category"] == "bread")` = first condition.
- `&` = both conditions must be true.
- `(dummy_df["price"] > 1.00)` = second condition.
- `( ) around each condition` = group each test clearly before joining them.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Iris question.
</div>

In [11]:
dummy_df[(dummy_df["category"] == "bread") & (dummy_df["price"] > 1.00)]

   item category  count  price
4  wrap    bread      5    1.4

**Question on the lesson dataset - Iris**

Filter the Iris table so it keeps only the rows where `species` equals `"virginica"` and `petal_width` is greater than `2.0`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Iris answer in the empty code cell under this orange box.
</div>

## Concept 8 - Two-Condition OR Filter With |

An OR filter keeps a row when at least one condition is true. A row can pass by meeting the first condition, the second condition, or both.

### Command Panel

```python
dummy_df[(dummy_df["category"] == "bread") | (dummy_df["price"] > 1.00)]
```

**Plain-English meaning**  
Keep rows where the `category` is `"bread"` or the `price` is greater than `1.00`.

**Code breakdown**

- `outer dummy_df[ ... ]` = keep rows from the table.
- `(dummy_df["category"] == "bread")` = first condition.
- `|` = either condition being true is enough.
- `(dummy_df["price"] > 1.00)` = second condition.
- `( ) around each condition` = group each test clearly before joining them.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Iris question.
</div>

In [12]:
dummy_df[(dummy_df["category"] == "bread") | (dummy_df["price"] > 1.00)]

     item category  count  price
0   bagel    bread     12   0.80
1    roll    bread     18   0.55
2  muffin     cake      7   1.20
3   scone     cake      9   1.10
4    wrap    bread      5   1.40

**Question on the lesson dataset - Iris**

Filter the Iris table so it keeps rows where `species` equals `"setosa"` or `sepal_length` is greater than `7.0`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Iris answer in the empty code cell under this orange box.
</div>

## Concept 9 - Parentheses Rule For Combined Conditions

When you combine conditions with `&` or `|`, each condition needs its own parentheses. The parentheses make it clear which test belongs together before the join happens.

### Command Panel

```python
dummy_df[(dummy_df["category"] == "bread") & (dummy_df["count"] > 10)]
```

**Plain-English meaning**  
Keep rows where the `category` is `"bread"` and the `count` is greater than `10`, with each condition wrapped in parentheses.

**Code breakdown**

- `(dummy_df["category"] == "bread")` = one complete condition, wrapped as one group.
- `&` = join the grouped conditions with AND.
- `(dummy_df["count"] > 10)` = the second complete condition, wrapped as one group.
- `outer dummy_df[ ... ]` = keep rows where the grouped test is true.
- `parentheses` = show Python exactly how the combined condition is grouped.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Iris question.
</div>

In [13]:
dummy_df[(dummy_df["category"] == "bread") & (dummy_df["count"] > 10)]

    item category  count  price
0  bagel    bread     12   0.80
1   roll    bread     18   0.55

**Question on the lesson dataset - Iris**

Write a combined Iris filter that uses parentheses correctly to keep only rows where `species` equals `"versicolor"` and `petal_length` is greater than `4.0`.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Iris answer in the empty code cell under this orange box.
</div>

## Concept 10 - Check Filtered Result Size With .shape

After filtering, you can ask how large the filtered table is. `shape` reports rows first and columns second, and it does not use `()` because it is a stored property, not a called tool.

### Command Panel

```python
dummy_df[dummy_df["category"] == "bread"].shape
```

**Plain-English meaning**  
Filter the table first, then show the size of the filtered result as `(rows, columns)`.

**Code breakdown**

- `dummy_df[dummy_df["category"] == "bread"]` = make the smaller filtered table first.
- `.` = reach into that filtered result.
- `shape` = the stored size property.
- `no ()` = no brackets because `shape` is a property, not a called tool.
- `(rows, columns)` = the order of the size result.

<div style="border:2px solid #1d4ed8; border-left:8px solid #1d4ed8; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Worked example code cell is directly below.</strong><br>
This blue-marked step is a demonstration. Read it and inspect the output before you answer the Iris question.
</div>

In [14]:
dummy_df[dummy_df["category"] == "bread"].shape

(3, 4)

**Question on the lesson dataset - Iris**

Filter the Iris table to keep only rows where `species` equals `"virginica"`, then use `.shape` to check the size of that filtered result.

<div style="border:2px solid #b45309; border-left:8px solid #b45309; padding:12px 14px; border-radius:8px; margin:10px 0;">
<strong>Your answer cell is directly below.</strong><br>
Type your Iris answer in the empty code cell under this orange box.
</div>

## Plain-English Findings

After you finish the learner cells, write three observations about what your filtered Iris results showed.

These should be about the data, not about the commands.

1. 
2. 
3. 

Also write one thing the filtered results do not tell you on their own.

-